//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public static class PauseMovement
		{
		static bool isStopped;
		static bool isFrozen;

		static PauseMovement() {
			isStopped = false;
			isFrozen = false;
		}

		public static void freezeTime() {
						isFrozen = true;
				}

		public static void unfreezeTime() {
						isFrozen = false;
				}

		public static void stopEverything() {
						isStopped = true;
				}

		public static void startEverything() {
						isStopped = false;
				}

		public static bool isTimeFrozen() {
						return isFrozen;
				}

		public static bool isTimeStopped() {
						return isStopped;
				}

		}
}

